export interface ElementData {
  symbol: string;
  num: number;
  name: string;
  metallic: string;
  state_of_matter: string;
  natural: string;
  fun_fact: string;
  valency: number | null
  atomic_radius: number | null
}

const elements: ElementData[] = [
  {
      "num": 1,
      "name": "Hydrogen",
      "symbol": "H",
      "valency": 1,
      "metallic": "Nonmetal",
      "atomic_radius": 53,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Hydrogen is the most abundant element in the universe, making up about 75% of all matter."
  },
  {
      "num": 2,
      "name": "Helium",
      "symbol": "He",
      "valency": 0,
      "metallic": "Nonmetal",
      "atomic_radius": 31,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Helium is the second lightest and second most abundant element in the universe."
  },
  {
      "num": 3,
      "name": "Lithium",
      "symbol": "Li",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 167,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Lithium is used in rechargeable batteries for mobile phones, laptops, and electric vehicles."
  },
  {
      "num": 4,
      "name": "Beryllium",
      "symbol": "Be",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 112,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Beryllium is used in aerospace material for its lightness and high melting point."
  },
  {
      "num": 5,
      "name": "Boron",
      "symbol": "B",
      "valency": 3,
      "metallic": "Metalloid",
      "atomic_radius": 87,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Boron is essential for plant growth and is used in glass and ceramics."
  },
  {
      "num": 6,
      "name": "Carbon",
      "symbol": "C",
      "valency": 4,
      "metallic": "Nonmetal",
      "atomic_radius": 70,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Carbon exists in different forms, such as graphite and diamond, showcasing its versatility."
  },
  {
      "num": 7,
      "name": "Nitrogen",
      "symbol": "N",
      "valency": 3,
      "metallic": "Nonmetal",
      "atomic_radius": 65,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Nitrogen makes up 78% of Earth's atmosphere and is essential for life."
  },
  {
      "num": 8,
      "name": "Oxygen",
      "symbol": "O",
      "valency": 2,
      "metallic": "Nonmetal",
      "atomic_radius": 60,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Oxygen makes up about 21% of the Earth's atmosphere and is essential for life."
  },
  {
      "num": 9,
      "name": "Fluorine",
      "symbol": "F",
      "valency": 1,
      "metallic": "Nonmetal",
      "atomic_radius": 50,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Fluorine is the most reactive element and is used in toothpaste to prevent cavities."
  },
  {
      "num": 10,
      "name": "Neon",
      "symbol": "Ne",
      "valency": 0,
      "metallic": "Nonmetal",
      "atomic_radius": 38,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Neon is famous for its use in neon signs due to its bright red-orange glow when electrified."
  },
  {
      "num": 11,
      "name": "Sodium",
      "symbol": "Na",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 186,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Sodium is highly reactive with water, producing hydrogen Gas and heat."
  },
  {
      "num": 12,
      "name": "Magnesium",
      "symbol": "Mg",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 160,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Magnesium is a vital element for the human body, important for muscle and nerve function."
  },
  {
      "num": 13,
      "name": "Aluminum",
      "symbol": "Al",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 143,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Aluminum is the most abundant Metal in Earth's crust and is used in a wide range of products."
  },
  {
      "num": 14,
      "name": "Silicon",
      "symbol": "Si",
      "valency": 4,
      "metallic": "Metalloid",
      "atomic_radius": 118,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Silicon is widely used in electronics as a semiconductor material."
  },
  {
      "num": 15,
      "name": "Phosphorus",
      "symbol": "P",
      "valency": 3,
      "metallic": "Nonmetal",
      "atomic_radius": 110,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Phosphorus is essential for life, forming part of DNA and ATP molecules."
  },
  {
      "num": 16,
      "name": "Sulfur",
      "symbol": "S",
      "valency": 2,
      "metallic": "Nonmetal",
      "atomic_radius": 100,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Sulfur is used in the production of sulfuric acid, one of the most important industrial chemicals."
  },
  {
      "num": 17,
      "name": "Chlorine",
      "symbol": "Cl",
      "valency": 1,
      "metallic": "Nonmetal",
      "atomic_radius": 99,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Chlorine is widely used to disinfect water and as a bleaching agent."
  },
  {
      "num": 18,
      "name": "Argon",
      "symbol": "Ar",
      "valency": 0,
      "metallic": "Nonmetal",
      "atomic_radius": 71,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Argon is a noble Gas that is chemically inert and is used in welding and lighting."
  },
  {
      "num": 19,
      "name": "Potassium",
      "symbol": "K",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 243,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Potassium is an essential element for human nutrition, important for cell function."
  },
  {
      "num": 20,
      "name": "Calcium",
      "symbol": "Ca",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 194,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Calcium is vital for bone and teeth formation and is the most abundant Metal in the human body."
  },
  {
      "num": 21,
      "name": "Scandium",
      "symbol": "Sc",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 184,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Scandium is often used in aerospace components due to its light weight and high strength."
  },
  {
      "num": 22,
      "name": "Titanium",
      "symbol": "Ti",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 176,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Titanium is known for its strength and corrosion resistance, making it ideal for aerospace and medical implants."
  },
  {
      "num": 23,
      "name": "Vanadium",
      "symbol": "V",
      "valency": 5,
      "metallic": "Metal",
      "atomic_radius": 171,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Vanadium is used in alloys to strengthen steel, especially for tools and automotive parts."
  },
  {
      "num": 24,
      "name": "Chromium",
      "symbol": "Cr",
      "valency": 6,
      "metallic": "Metal",
      "atomic_radius": 166,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Chromium is used to make stainless steel and to coat other Metals to prevent corrosion."
  },
  {
      "num": 25,
      "name": "Manganese",
      "symbol": "Mn",
      "valency": 7,
      "metallic": "Metal",
      "atomic_radius": 161,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Manganese is essential in steel production, improving hardness and durability."
  },
  {
      "num": 26,
      "name": "Iron",
      "symbol": "Fe",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 156,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Iron is the most widely used Metal, primarily in construction and manufacturing."
  },
  {
      "num": 27,
      "name": "Cobalt",
      "symbol": "Co",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 152,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Cobalt is used in batteries and magnetic alloys, as well as blue pigments for ceramics."
  },
  {
      "num": 28,
      "name": "Nickel",
      "symbol": "Ni",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 149,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Nickel is highly resistant to corrosion, making it useful in alloys like stainless steel."
  },
  {
      "num": 29,
      "name": "Copper",
      "symbol": "Cu",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 145,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Copper has been used by humans for thousands of years and is an excellent conductor of electricity."
  },
  {
      "num": 30,
      "name": "Zinc",
      "symbol": "Zn",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 142,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Zinc is essential for human health and is commonly used to galvanize other Metals to prevent rust."
  },
  {
      "num": 31,
      "name": "Gallium",
      "symbol": "Ga",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 136,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Gallium can melt in your hand, and is used in semiconductors and LEDs."
  },
  {
      "num": 32,
      "name": "Germanium",
      "symbol": "Ge",
      "valency": 4,
      "metallic": "Metalloid",
      "atomic_radius": 125,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Germanium is used in fiber optics and infrared optics due to its transparency to infrared light."
  },
  {
      "num": 33,
      "name": "Arsenic",
      "symbol": "As",
      "valency": 3,
      "metallic": "Metalloid",
      "atomic_radius": 114,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Arsenic is toxic and was historically used as a poison, but also has applications in semiconductors."
  },
  {
      "num": 34,
      "name": "Selenium",
      "symbol": "Se",
      "valency": 2,
      "metallic": "Nonmetal",
      "atomic_radius": 103,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Selenium is used in electronics, glassmaking, and as a dietary supplement."
  },
  {
      "num": 35,
      "name": "Bromine",
      "symbol": "Br",
      "valency": 1,
      "metallic": "Nonmetal",
      "atomic_radius": 94,
      "state_of_matter": "Liquid",
      "natural": "Natural",
      "fun_fact": "Bromine is the only Nonmetallic element that is a Liquid at room temperature."
  },
  {
      "num": 36,
      "name": "Krypton",
      "symbol": "Kr",
      "valency": 0,
      "metallic": "Nonmetal",
      "atomic_radius": 88,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Krypton is a noble Gas used in lighting and photography, particularly in high-performance lamps."
  },
  {
      "num": 37,
      "name": "Rubidium",
      "symbol": "Rb",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 265,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Rubidium is highly reactive and is used in atomic clocks, fireworks, and research."
  },
  {
      "num": 38,
      "name": "Strontium",
      "symbol": "Sr",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 219,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Strontium is used in fireworks for red colors, and in medical imaging to track calcium in the body."
  },
  {
      "num": 39,
      "name": "Yttrium",
      "symbol": "Y",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 212,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Yttrium is used in superconductors, lasers, and is essential in producing certain LED lights."
  },
  {
      "num": 40,
      "name": "Zirconium",
      "symbol": "Zr",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 206,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Zirconium is used in nuclear reactors and surgical instruments due to its high resistance to corrosion."
  },
  {
      "num": 41,
      "name": "Niobium",
      "symbol": "Nb",
      "valency": 5,
      "metallic": "Metal",
      "atomic_radius": 198,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Niobium is used in superconducting magnets and in alloys for jet engines."
  },
  {
      "num": 42,
      "name": "Molybdenum",
      "symbol": "Mo",
      "valency": 6,
      "metallic": "Metal",
      "atomic_radius": 190,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Molybdenum is essential for plant growth and is used in steel alloys to increase strength."
  },
  {
      "num": 43,
      "name": "Technetium",
      "symbol": "Tc",
      "valency": 7,
      "metallic": "Metal",
      "atomic_radius": 183,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Technetium is the first element to be artificially produced, and it is used in medical imaging."
  },
  {
      "num": 44,
      "name": "Ruthenium",
      "symbol": "Ru",
      "valency": 8,
      "metallic": "Metal",
      "atomic_radius": 178,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Ruthenium is used in electrical contacts and as a catalyst in chemical reactions."
  },
  {
      "num": 45,
      "name": "Rhodium",
      "symbol": "Rh",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 173,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Rhodium is one of the rarest and most valuable precious Metals, used in catalytic converters."
  },
  {
      "num": 46,
      "name": "Palladium",
      "symbol": "Pd",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 169,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Palladium is used in electronics, jewelry, and as a catalyst in chemical reactions."
  },
  {
      "num": 47,
      "name": "Silver",
      "symbol": "Ag",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 165,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Silver has the highest electrical conductivity of any Metal."
  },
  {
      "num": 48,
      "name": "Cadmium",
      "symbol": "Cd",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 161,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Cadmium is primarily used in rechargeable batteries and pigments."
  },
  {
      "num": 49,
      "name": "Indium",
      "symbol": "In",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 156,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Indium is used in touchscreens and LCDs."
  },
  {
      "num": 50,
      "name": "Tin",
      "symbol": "Sn",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 145,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Tin is used to coat other Metals to prevent corrosion, as well as in soldering."
  },
  {
      "num": 51,
      "name": "Antimony",
      "symbol": "Sb",
      "valency": 3,
      "metallic": "Metalloid",
      "atomic_radius": 133,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Antimony is used in fire retardants and semiconductors."
  },
  {
      "num": 52,
      "name": "Tellurium",
      "symbol": "Te",
      "valency": 2,
      "metallic": "Metalloid",
      "atomic_radius": 123,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Tellurium is used in thermoelectric devices and solar panels."
  },
  {
      "num": 53,
      "name": "Iodine",
      "symbol": "I",
      "valency": 1,
      "metallic": "Nonmetal",
      "atomic_radius": 115,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Iodine is essential for thyroid function and is used as a disinfectant."
  },
  {
      "num": 54,
      "name": "Xenon",
      "symbol": "Xe",
      "valency": 0,
      "metallic": "Nonmetal",
      "atomic_radius": 108,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Xenon is used in specialized lamps, such as flashlights and car headlights."
  },
  {
      "num": 55,
      "name": "Cesium",
      "symbol": "Cs",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 265,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Cesium is used in atomic clocks and in oil drilling fluids."
  },
  {
      "num": 56,
      "name": "Barium",
      "symbol": "Ba",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 215,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Barium is used in medical imaging for X-ray diagnostics."
  },
  {
      "num": 57,
      "name": "Lanthanum",
      "symbol": "La",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 195,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Lanthanum is used in camera lenses and in hybrid vehicle batteries."
  },
{"num": 72, "name": "Hafnium", "symbol": "Hf", "valency": 4, "metallic": "Metal", "atomic_radius": 150, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Hafnium is used in nuclear control rods and in superalloys for jet engines."},
  {"num": 73, "name": "Tantalum", "symbol": "Ta", "valency": 5, "metallic": "Metal", "atomic_radius": 140, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Tantalum is highly corrosion-resistant and is used in electronics, such as capacitors and mobile phones."},
  {"num": 74, "name": "Tungsten", "symbol": "W", "valency": 6, "metallic": "Metal", "atomic_radius": 135, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Tungsten has the highest melting point of any Metal and is used in light bulb filaments and cutting tools."},
  {"num": 75, "name": "Rhenium", "symbol": "Re", "valency": 7, "metallic": "Metal", "atomic_radius": 130, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Rhenium is used in jet engines and in high-temperature superalloys."},
  {"num": 76, "name": "Osmium", "symbol": "Os", "valency": 8, "metallic": "Metal", "atomic_radius": 125, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Osmium is the densest naturally occurring element and is used in fountain pen tips and electrical contacts."},
  {"num": 77, "name": "Iridium", "symbol": "Ir", "valency": 8, "metallic": "Metal", "atomic_radius": 120, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Iridium is highly corrosion-resistant and is used in spark plugs and crucibles for high-temperature applications."},
  {
      "num": 78,
      "name": "Platinum",
      "symbol": "Pt",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 115,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Platinum is used in catalytic converters, jewelry, and laboratory equipment."
  },
  {
      "num": 79,
      "name": "Gold",
      "symbol": "Au",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 110,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Gold is a highly valued precious Metal, known for its rarity and resistance to tarnish."
  },
  {
      "num": 80,
      "name": "Mercury",
      "symbol": "Hg",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 105,
      "state_of_matter": "Liquid",
      "natural": "Natural",
      "fun_fact": "Mercury is the only Metal that is Liquid at room temperature, and it has been used in thermometers and barometers."
  },
  {
      "num": 81,
      "name": "Thallium",
      "symbol": "Tl",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 170,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Thallium is used in electronics and was historically used as a poison."
  },
  {
      "num": 82,
      "name": "Lead",
      "symbol": "Pb",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 180,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Lead is highly toxic but has been used in plumbing and paints historically."
  },
  {
      "num": 83,
      "name": "Bismuth",
      "symbol": "Bi",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 160,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Bismuth is the heaviest non-radioactive element and is used in cosmetics and medical treatments."
  },
  {
      "num": 84,
      "name": "Polonium",
      "symbol": "Po",
      "valency": 2,
      "metallic": "Metalloid",
      "atomic_radius": 140,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Polonium is highly radioactive and was famously used to poison Alexander Litvinenko."
  },
  {
      "num": 85,
      "name": "Astatine",
      "symbol": "At",
      "valency": 1,
      "metallic": "Metalloid",
      "atomic_radius": 127,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Astatine is the rarest naturally occurring element on Earth."
  },
  {
      "num": 86,
      "name": "Radon",
      "symbol": "Rn",
      "valency": 0,
      "metallic": "Nonmetal",
      "atomic_radius": 120,
      "state_of_matter": "Gas",
      "natural": "Natural",
      "fun_fact": "Radon is a radioactive Gas that can accumulate in buildings, posing health risks."
  },
  {
      "num": 87,
      "name": "Francium",
      "symbol": "Fr",
      "valency": 1,
      "metallic": "Metal",
      "atomic_radius": 260,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Francium is extremely rare and highly radioactive, with a half-life of only 22 minutes."
  },
  {
      "num": 88,
      "name": "Radium",
      "symbol": "Ra",
      "valency": 2,
      "metallic": "Metal",
      "atomic_radius": 215,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Radium is highly radioactive and was once used in luminous paints."
  },
  {
      "num": 89,
      "name": "Actinium",
      "symbol": "Ac",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 188,
      "state_of_matter": "Solid",
      "natural": "Natural",
      "fun_fact": "Actinium is a radioactive element used as a neutron source."
  },
  
  {
      "num": 104,
      "name": "Rutherfordium",
      "symbol": "Rf",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 157,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Rutherfordium is named after Ernest Rutherford, who discovered the nucleus."
  },
  {
      "num": 105,
      "name": "Dubnium",
      "symbol": "Db",
      "valency": 5,
      "metallic": "Metal",
      "atomic_radius": 149,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Dubnium is named after the Russian town of Dubna, where it was discovered."
  },
  {
      "num": 106,
      "name": "Seaborgium",
      "symbol": "Sg",
      "valency": 6,
      "metallic": "Metal",
      "atomic_radius": 143,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Seaborgium is named after Glenn T. Seaborg, an American chemist."
  },
  {
      "num": 107,
      "name": "Bohrium",
      "symbol": "Bh",
      "valency": 7,
      "metallic": "Metal",
      "atomic_radius": 141,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Bohrium is named after Niels Bohr, a famous physicist."
  },
  {
      "num": 108,
      "name": "Hassium",
      "symbol": "Hs",
      "valency": 8,
      "metallic": "Metal",
      "atomic_radius": 134,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Hassium is named after the German state of Hesse."
  },
  {
      "num": 109,
      "name": "Meitnerium",
      "symbol": "Mt",
      "valency": 7,
      "metallic": "Metal",
      "atomic_radius": 128,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Meitnerium is named after Lise Meitner, an Austrian-Swedish physicist."
  },
  {
      "num": 110,
      "name": "Darmstadtium",
      "symbol": "Ds",
      "valency": 6,
      "metallic": "Metal",
      "atomic_radius": 126,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Darmstadtium is named after the German city of Darmstadt, where it was first synthesized."
  },
  {
      "num": 111,
      "name": "Roentgenium",
      "symbol": "Rg",
      "valency": 5,
      "metallic": "Metal",
      "atomic_radius": 121,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Roentgenium is named after Wilhelm R\u00f6ntgen, the discoverer of X-rays."
  },
  {
      "num": 112,
      "name": "Copernicium",
      "symbol": "Cn",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 119,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Copernicium is named after Nicolaus Copernicus, the astronomer who proposed the heliocentric model."
  },
  {
      "num": 113,
      "name": "Nihonium",
      "symbol": "Nh",
      "valency": 3,
      "metallic": "Metal",
      "atomic_radius": 118,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Nihonium is named after Japan (Nihon), where it was discovered."
  },
  {
      "num": 114,
      "name": "Flerovium",
      "symbol": "Fl",
      "valency": 4,
      "metallic": "Metal",
      "atomic_radius": 116,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Flerovium is named after the Russian Flerov Laboratory of Nuclear Reactions."
  },
  {
      "num": 115,
      "name": "Moscovium",
      "symbol": "Mc",
      "valency": 5,
      "metallic": "Metal",
      "atomic_radius": 114,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Moscovium is named after Moscow, Russia."
  },
  {
      "num": 116,
      "name": "Livermorium",
      "symbol": "Lv",
      "valency": 6,
      "metallic": "Metal",
      "atomic_radius": 111,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Livermorium is named after the Lawrence Livermore National Laboratory in California."
  },
  {
      "num": 117,
      "name": "Tennessine",
      "symbol": "Ts",
      "valency": 7,
      "metallic": "Metal",
      "atomic_radius": 110,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Tennessine is named after the state of Tennessee, home to Oak Ridge National Laboratory."
  },
  {
      "num": 118,
      "name": "Oganesson",
      "symbol": "Og",
      "valency": 8,
      "metallic": "Metal",
      "atomic_radius": 109,
      "state_of_matter": "Solid",
      "natural": "Synthetic",
      "fun_fact": "Oganesson is named after Yuri Oganessian, a physicist known for his work in superheavy elements."
  },



  {
    "num": 58,
    "name": "Cerium",
    "symbol": "Ce",
    "valency": 4,
    "metallic": "Metal",
    "atomic_radius": 185,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Cerium is the most abundant rare earth element and is used in catalytic converters."
},
{
    "num": 59,
    "name": "Praseodymium",
    "symbol": "Pr",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 185,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Praseodymium is used in aircraft engines and in creating strong magnets."
},
{
    "num": 60,
    "name": "Neodymium",
    "symbol": "Nd",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 185,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Neodymium is used in powerful magnets for electronics, such as in hard drives and headphones."
},
{
    "num": 61,
    "name": "Promethium",
    "symbol": "Pm",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 183,
    "state_of_matter": "Solid",
    "natural": "Synthetic",
    "fun_fact": "Promethium is radioactive and is used in specialized batteries for pacemakers."
},
{
    "num": 62,
    "name": "Samarium",
    "symbol": "Sm",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 180,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Samarium is used in magnets, lasers, and nuclear reactors."
},
{
    "num": 63,
    "name": "Europium",
    "symbol": "Eu",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 180,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Europium is used in phosphorescent and fluorescent materials, such as in TV screens."
},
{
    "num": 64,
    "name": "Gadolinium",
    "symbol": "Gd",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 180,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Gadolinium is used in medical imaging as a contrast agent for MRI scans."
},
{
    "num": 65,
    "name": "Terbium",
    "symbol": "Tb",
    "valency": 3,
    "metallic": "Metal",
    "atomic_radius": 177,
    "state_of_matter": "Solid",
    "natural": "Natural",
    "fun_fact": "Terbium is used in green phosphors for TV screens and in Solid-state devices."
},

{"num": 66, "name": "Dysprosium", "symbol": "Dy", "valency": 3, "metallic": "Metal", "atomic_radius": 178, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Dysprosium is used in hard disk drives and in nuclear reactors."},
{"num": 67, "name": "Holmium", "symbol": "Ho", "valency": 3, "metallic": "Metal", "atomic_radius": 176, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Holmium has the highest magnetic strength of any element and is used in magnetic devices."},
{"num": 68, "name": "Erbium", "symbol": "Er", "valency": 3, "metallic": "Metal", "atomic_radius": 175, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Erbium is used in fiber optic communication systems and in lasers."},
{"num": 69, "name": "Thulium", "symbol": "Tm", "valency": 3, "metallic": "Metal", "atomic_radius": 173, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Thulium is used in portable X-ray devices and as a radiation source."},
{"num": 70, "name": "Ytterbium", "symbol": "Yb", "valency": 3, "metallic": "Metal", "atomic_radius": 170, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Ytterbium is used in atomic clocks and in materials to improve the grain structure of stainless steel."},
{"num": 71, "name": "Lutetium", "symbol": "Lu", "valency": 3, "metallic": "Metal", "atomic_radius": 160, "state_of_matter": "Solid", "natural": "Natural", "fun_fact": "Lutetium is used in PET scan detectors and as a catalyst in petroleum refining."},
{
  "num": 90,
  "name": "Thorium",
  "symbol": "Th",
  "valency": 4,
  "metallic": "Metal",
  "atomic_radius": 180,
  "state_of_matter": "Solid",
  "natural": "Natural",
  "fun_fact": "Thorium can be used as a nuclear fuel and is being researched as a safer alternative to uranium."
},
{
  "num": 91,
  "name": "Protactinium",
  "symbol": "Pa",
  "valency": 5,
  "metallic": "Metal",
  "atomic_radius": 180,
  "state_of_matter": "Solid",
  "natural": "Natural",
  "fun_fact": "Protactinium is a highly toxic radioactive element used in scientific research."
},
{
  "num": 92,
  "name": "Uranium",
  "symbol": "U",
  "valency": 6,
  "metallic": "Metal",
  "atomic_radius": 175,
  "state_of_matter": "Solid",
  "natural": "Natural",
  "fun_fact": "Uranium is used as a fuel in nuclear reactors and in atomic bombs."
},
{
  "num": 93,
  "name": "Neptunium",
  "symbol": "Np",
  "valency": 5,
  "metallic": "Metal",
  "atomic_radius": 175,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Neptunium is a radioactive element and a byproduct of uranium in nuclear reactors."
},
{
  "num": 94,
  "name": "Plutonium",
  "symbol": "Pu",
  "valency": 6,
  "metallic": "Metal",
  "atomic_radius": 175,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Plutonium is used in nuclear weapons and reactors, but it's highly toxic and radioactive."
},
{
  "num": 95,
  "name": "Americium",
  "symbol": "Am",
  "valency": 6,
  "metallic": "Metal",
  "atomic_radius": 175,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Americium is used in smoke detectors, despite its radioactivity."
},
{
  "num": 96,
  "name": "Curium",
  "symbol": "Cm",
  "valency": 6,
  "metallic": "Metal",
  "atomic_radius": 174,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Curium is named after Marie Curie and is used in space exploration."
},
{
  "num": 97,
  "name": "Berkelium",
  "symbol": "Bk",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 170,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Berkelium was first synthesized at the University of California, Berkeley."
},
{
  "num": 98,
  "name": "Californium",
  "symbol": "Cf",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 170,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Californium is used in neutron radiography and cancer treatment."
},
{
  "num": 99,
  "name": "Einsteinium",
  "symbol": "Es",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 170,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Einsteinium is named after Albert Einstein and is produced in minute quantities."
},
{
  "num": 100,
  "name": "Fermium",
  "symbol": "Fm",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 170,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Fermium is named after Enrico Fermi, the creator of the first nuclear reactor."
},
{
  "num": 101,
  "name": "Mendelevium",
  "symbol": "Md",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 170,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Mendelevium is named after Dmitri Mendeleev, the creator of the Periodic Table."
},
{
  "num": 102,
  "name": "Nobelium",
  "symbol": "No",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 160,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Nobelium is named after Alfred Nobel, the inventor of dynamite and founder of the Nobel Prize."
},
{
  "num": 103,
  "name": "Lawrencium",
  "symbol": "Lr",
  "valency": 3,
  "metallic": "Metal",
  "atomic_radius": 160,
  "state_of_matter": "Solid",
  "natural": "Synthetic",
  "fun_fact": "Lawrencium is named after Ernest Lawrence, the inventor of the cyclotron."
}
]

export const elementMap = new Map();
elements.forEach(element => {
  elementMap.set(element.name.toLowerCase(), element); 
});

console.log(elementMap)